M48
; DRILL file {KiCad 9.0.0} date 2025-03-25T22:48:29+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-25T22:48:29+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X2.0937Y-2.4896
X2.3213Y-2.4896
T2
X2.5213Y-2.5783
X2.789Y-2.5783
M30
